spring.application.name=TO-DO

## -- POSTGRESQL -- ##
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

## -- HIBERNATE -- ##
spring.jpa.hibernate.dll-auto=none
spring.jpa.show-sql=true

## -- FLYWAY --##
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

